const c = G = MSOLAR = 1

const MASS_UNIT_TO_SI       = 1.989e30
const LENGTH_UNIT_TO_SI     = 1.477e3
const TIME_UNIT_TO_SI       = 4.927e-6
const SI_TO_MASS_UNIT       = MASS_UNIT_TO_SI^(-1)
const SI_TO_LENGTH_UNIT     = LENGTH_UNIT_TO_SI^(-1)
const SI_TO_TIME_UNIT       = TIME_UNIT_TO_SI^(-1)

const PRESSURE_UNIT_TO_SI   = MASS_UNIT_TO_SI*LENGTH_UNIT_TO_SI^(-1)*TIME_UNIT_TO_SI^(-2)
const SI_TO_PRESSURE_UNIT   = PRESSURE_UNIT_TO_SI^(-1)

const ħ = 1.054e-34*SI_TO_MASS_UNIT*SI_TO_LENGTH_UNIT^2*SI_TO_TIME_UNIT^(-1)
const mₙ = 1.674e-27*SI_TO_MASS_UNIT
